sentences = [
    'I can\'t stop thinking about you.',
    'You\'ll always be my girl.',
    'Since the day I met you, my life has never been the same.',
    'I love making you laugh.',
    'I love you more than pepperoni pizza.',
    'You\'re my dream girl.',
    'You ground me.',
    'You\'re kinda, maybe a little, sorta, pretty much always on my mind.',
    'I would follow you anywhere.',
    'When I\'m with you, everything feels right.',
    'I\'ll keep loving you until the day I die...and even after that, if possible.',
    'When I\'m with you, nothing else matters.',
    'Do you have any idea how much I adore you?',
    'All love is sweet, but ours is the sweetest.',
    'Because you\'re in my life, I know true love exists.',
    'You bring out the best in me.',
    'We are two peas in a pod.',
    'You have that sparkle.',
    'I love you today. I will love you tomorrow. And I\'ll keep on loving you every day after that, too.',
    'I can\'t believe a girl like you exists and that I\'m lucky enough to have found her.',
    '\'To me, you are perfect.\' — Love Actually',
    'Know that no matter where life takes us, you will always be the only one for me.',
    'My favorite part of every day is the time I get to spend with you.',
    'When others talk about their greatest achievements and things they are most \
        proud of, the only thing that comes to mind is you.',
    'I love seeing you blush.',
    'Only you can give me that feeling.',
    'I\'m missing you.',
    'Now that I\'ve found you, I\'m never going to let you go.',
    'You are the prettiest girl I\'ve ever seen.',
    'Whenever I count my blessings, you are at the top of my list.',
    'You make me so incredibly happy.',
    'I am the luckiest man alive because I get to call you mine.',
    'When we\'re together, nothing else matters.',
    'There\'s no better match than me and you.',
    'I\'d follow you anywhere.',
    'No one understands me like you do.',
    'This morning, I jumped out of bed because I was so excited to see you.',
    'Keep in mind that you complete me in such a unique and wonderful way.',
    'This Christmas, the only thing I want from Santa is you!',
    'You know exactly what I need, even if I don\'t say it.',
    'You\'re the peanut butter to my jelly.',
    'My favorite sound in the universe is your laugh.',
    'I love you not only for who you are, but also for who I become when I am with you.',
    'I can\'t get enough of you.',
    'Having you in my life means I\'ll always have someone I can rely on. Even \
        when you\'re not with me, I know you\'re just a phone call away.',
    'Your voice is my favorite sound, your name is my favorite word, and your hug is my favorite place to be.',
    'You\'re cute. Can I keep you forever?',
    'I feel so lucky to be with you.',
    'Going through difficult times with you has only strengthened our relationship.',
    'I have waited all of my life to be with someone like you.',
    'You make every day better.',
    'You\'re the woman I\'ve always wished for.',
    'There\'s nothing I don\'t like about you.',
    'I have big plans for us and our future.',
    'Some guys seek glory, while others seek money. But, girl, all I want is for you to be by my side.',
    'I was so unproductive today. All I did was sit around thinking about you.',
    'The best part of me is you.',
    'Ever since I met you, no one else has been worth thinking about.',
    'I would do anything for you.',
    'My whole world revolves around you.',
    'Life with you is an adventure.',
    'You\'re my best friend.',
    'If I had to do it all over again, I would still choose you.',
    'You are all my heart ever talks about.',
    'Whenever I tell you goodbye, I instantly start counting down the seconds until I can see you again.',
    'If I could get a star for every time you crossed my mind, I\'m sure I\'d own the entire galaxy by now.',
    'Sweet dreams...I hope I\'m in them.',
    'Even when you\'re not trying, you still look gorgeous.',
    'I know you love me because you put up with me even when I\'m at my worst.',
    'We have such great chemistry.',
    'The first time I saw you, my heart skipped a beat.',
    'The thought of being with you is the only thing that gets me through a rough day.',
    'I made a wish, and you came true.',
    'You\'re the melody to every love song.',
    'When I think about the future, all I see is you.',
    'I really want to kiss you right now.',
    'I\'m so grateful for you and all the things you do for me.',
    'If my life was a puzzle, you\'d be the final piece that ties it all together.',
    'I\'m counting down the minutes until I can see you again.',
    'No one makes me laugh like you do.',
    'It\'s not my fault I fell for you–you tripped me!',
    'I can\'t wait to fall asleep beside you.',
    'I\'ll always be there for you!',
    'I love the feeling of doing life with you.',
    'You are so cute I could just eat you up!',
    'I am really glad you chose me out of everyone else.',
    'You aren\'t just my moon, stars, and sun. You are my entire universe.',
    'My face hurts from smiling so much whenever I\'m with you.',
    'Let\'s flip a coin: Heads I\'m yours. Tails you\'re mine.',
    'The concept of soulmates seemed so far-fetched to me until I met you.',
    'You look ravishing tonight.',
    'Come here please—I want to be closer to you.',
    'You\'re the answer to all my prayers.',
    'I love the way you make me feel.',
    'I\'ve been missing you for the past 24 hours, 1440 minutes, and 86400 seconds.',
    'You helped me discover pieces of myself I never knew existed.',
    'It\'s a blessing to have you in my life.',
    'May I have a kiss? I promise to give it back.',
    'It\'s difficult to put into words just how much I love you.',
    'If you were a library book, I\'d check you out and never return you.',
    'I might as well call you Google, because you are everything I\'m looking for.',
    'No one will ever be like you.',
    'Your kisses make me melt.',
    'I love it when I catch you looking at me.',
    'All I want to do is make you happy.',
    'Everything about you captivates me.',
    'I\'ll always be yours—no matter what.',
    'Just one look at you and my heart skips a beat.',
    'I never imagined I could love you any more than I already do, but I was wrong.',
    'I heard kissing burns calories. Want to work out with me?',
    'I hope your day is as nice as your smile.',
    'I hope that someday we\'ll look back on our relationship and our only \
        regret will be that we wish we had started it sooner.',
    'Every time I see you, my day gets 10x better.',
    'How do you always look so cute?!',
    'Waking up next to you is my favorite thing.',
    'Let\'s start a new tradition together.',
    'I feel at ease whenever I\'m with you.',
    'If you keep being so sweet, I\'ll have diabetes very soon.',
    'I can\'t seem to get you out of my head, no matter how hard I try.',
    'I love how we always finish each other\'s sentences.',
    'You are the only one who has the key to my heart.',
    'I never thought I could score a girlfriend like you.',
    'You always know exactly what to say to make me feel better.',
    'You are such a thoughtful girlfriend.',
    'Thank you for always being there for me.',
    'If loving you is wrong, then I don\'t ever want to be right.',
    'I would love to spend my whole life in your arms.',
    'I\'m absolutely crazy about you.',
    'I love making you smile.',
    'I feel safe whenever I\'m with you.',
    'I wish I could hold you in my arms for the rest of my life and never let go.',
    'I\'m always having a great day whenever I get to spend it with you.',
    'When you\'re in the room, no one else matters.',
    'I love you because you treat me like a princess.',
    'My heart starts racing every time I see you.',
    'Related: Cute Names for Your Boyfriend',
    'You\'re my everything.',
    'You always know exactly what to say to make me feel better.',
    'You\'re the first thing I think of every time I wake up and the last thing I think of before I go to sleep.',
    'I\'d rather be broke, than give you up for all the money in the world.',
    'Every time I get a text, I hope it\'s from you.',
    'You are my number one priority.',
    'I\'ve been fantasizing about you all day.',
    'You make the world a brighter place.',
    'You\'re the only person I\'ll ever need in my life.',
    'I can\'t breathe without you.',
    'You\'re my very best friend.',
    'You fulfill my needs in every aspect.',
    'You are the one man I want, and I will never settle for anyone else.',
    'When I\'m not with you, I feel lost.',
    'When you love someone and they love you back, you know you\'ve found happiness. I\'m happy because I have you.',
    'My favorite place to be is in your arms.',
    'I will never give up on us.',
    'All I\'ve ever wanted is you.',
    'I dream of spending the rest of my life with you.',
    'I wouldn\'t change a single thing about you. You are perfect just the way you are.',
    'You\'re the love of my life—my one true soulmate.',
    'I never knew what love was until I met you.',
    'You own my heart.',
    'Even one day apart is one too many.',
    'My feelings for you know no end.',
    'You make me feel like a better man.',
    'I lose myself while I\'m with you, and when I\'m not with you, I want to be lost all over again.',
    'I feel like the luckiest guy alive every time I get to walk into a room holding your hand.',
    'Losing you is my biggest fear.',
    'You\'re always on my mind.',
    'The sound of your name makes my heart skip a beat.',
    'If I had to choose between breathing and loving you, I would say I love you with my last breath.',
    'I don\'t want to grow old, but if I have to, I want to grow old with you.',
    'I wish I was an octopus so I could hold have more arms to hold you.',
    'You\'re everything I want, everything I need, and everything I didn\'t know to ask for.',
    'Every love story is wonderful, but ours is my favorite.',
    'The only place I want to be when I\'m with you is closer.',
    'You may just be one person, but to me you are the world.',
    'Every romantic song, every sweet saying, every love story—they all remind me of you.',
    'I want to be your favorite hello and your hardest goodbye.',
    'Nothing is as much fun as it is when you\'re there doing it with me.',
    'How do you always look so beautiful?',
    'Nothing or no one will ever get in the way of me loving you.',
    'I love you completely—even the parts of you that you wish you could change.',
    'Life without you isn\'t really life at all.',
    'You\'re the best thing that\'s ever happened to me.',
    'You are always worth waking up for.',
    'I want to be the reason you smile whenever you get a new text and look at your phone.',
    'Every minute I spend by your side, the world seems absolutely perfect.',
    'I fall for you more and more every day.',
    'I\'ve been looking for you my entire life.',
    'Life without you is pointless, like a broken pencil.',
    'I adore every piece of you, from the top of your head to the tips of your toes.',
    'When I\'m around you, I love who I become.',
    'When I tell you I love you, I don\'t say it because I should. I say it to \
        remind you that you\'re the best thing that\'s ever happened to me.',
    'If I could catch a star for every time you made me smile, I\'d have the entire galaxy in the palm of my hand.',
    'There\'s nowhere I\'d rather be than here, by you.',
    'I usually don\'t get attached easily, but that all changed the moment I met you.',
    'I wish I could take you with me everywhere I go.',
    'The sound of your laugh is music to my ears.',
    'I can\'t wait to make more memories with you.',
    'You make me so happy just by being yourself.',
    'Thank you for loving me.',
    'I want to grow old with you.',
    'Being with you feels so right.',
    'Your intelligence astounds me.',
    'I never get tired of looking at you.',
    'Hearing your voice brings me so much joy.',
    'Thank you for supporting me.',
    'I love being in love with you.',
    'Thank you for looking after me.',
    'Thank you for always being there for me.',
    'I love the unique way you giggle.',
    'I can\'t get enough of you.',
    'I love being with so much, I wish time could stand still when we\'re together.',
    'Seeing you smile is the best part of my day.',
    'There is no one else like you. You are the best',
    'I\'m always here for you.',
    'You always have the best ideas.',
    'You make me feel special.',
    'I am the luckiest man for getting to have you by my side.',
    'You brighten up the room every time you laugh.',
    'I\'m so glad you chose me.',
    'You have my heart.',
    'I feel blessed to have you in my life.',
    'Falling in love is great, but being in love with you is even better.',
    'I don\'t know what I\'d do without you.',
    'You are truly gorgeous.',
    'You mean the world to me.',
    'I love doing life with you.',
    'Being with you trumps all other plans.',
    'When I hold you in my arms, I feel so lucky.',
    'Thank you for listening.',
    'Adventures with you are my favorite.',
    'You make the world so much more beautiful.',
    'I\'m in awe of what a wonderful person you are.',
    'You inspire me to be a better man.',
    'You are my lucky charm.',
    'If you let me, I would hold you forever.',
    'When I\'m with you, I feel like I found what I was looking for.',
    'There aren\'t enough stars in the sky to show you how much you brighten up my day.',
    'I could stare into your eyes forever.',
    'Your presence brings the best out of me.',
    'My cheeks hurt from smiling so much around you.',
    'I still feel butterflies around you.',
    'I admire your {0}.',
    'I\'m thankful that {0}.',
    'I appreciate that you {0}.',
    'You have the best {0}.',
    'I love you more than I did yesterday, but not as much as I will tomorrow.',
    'You take my breath away.',
    'You are the only one I\'ll ever love.',
    'I hope you know how special you are to me.',
    'It took a long time for you to enter my life, but the wait was totally worth it.',
    'They say love hurts, but if it means I get to be with you, I\'m willing to take that risk.',
    'You are my North, East, South, and West. Everywhere I go, all roads lead back to you.',
    'Some people say you only fall in love once, but I fall in love all over again every time I see your smile.',
    'I thought \'true love\' was just a fairy tale. Then...I met you.',
    'When I picture my future, all I see is you.',
    'I used to think that happiness began with an H, but now I realize that it begins with U.',
    'You deserve the world.',
    'You take such good care of me.',
    'I love holding your hand.',
    'I became a better woman when I found you.',
    'Every day you push me higher.',
    'I\'d go crazy if something ever happened to you.',
    'For the first time in my life, I don\'t have to make an effort to be happy. It just happens when I\'m with you.',
    'You\'re the center of my universe.',
    'Words are not enough to explain how much I love you.',
    'I\'m living the perfect life because I start and end each day with you.',
    'I still get butterflies every time I see you.',
    'I love the feeling of being loved by you.',
    'I\'d give anything just to be with you.',
    'When I\'m with you, the world looks so perfect.',
    'Life with you is like a dream.',
    'I\'m so addicted to you and the way you love me.',
    'How did I ever get so lucky to be your girl!',
    'Your touch sends chills up and down my spine.',
    'I\'m sure the other girls are envious that I get to have you all to myself.',
    'I had no idea what true love was until I met you.',
    'I love you — not just for who you are but for who I am when I\'m with you.',
    'You\'re the only woman I want to spend the rest of my life with.',
    'No matter what we\'re doing, the time I spend with you is the best time of my life.',
    'Thank you for always being there for me. You know me better than anyone. And you\'re still here.',
    'When I think of my future, what I want to see — more than anything — is you.',
    'The story of you and me is my favorite epic love story.',
    'You\'re the one person I can count on to see the best in me.',
    'You\'re my person. I never thought I\'d want someone in my life as badly as I want you.',
    'All that time spent planning my career, and the one thing I want to be more than anything is yours.',
    'With you, I feel comfortable just being myself. But I also want to be better.',
    'You\'re my favorite conversation partner. You always know just what to say.',
    'couple smiling facing each other romantic things to say to your girlfriend',
    'If everyone looking for a girlfriend found someone like you, this world \
        would be a completely different place. It would be better in all the ways that matter.',
    'I\'ve never wanted anything more than to make this work and to spend the rest of my life loving you.',
    'Loving you is the best choice I ever made. And I\'ll make it every day for the rest of my life.',
    'I keep wondering how someone like me ended up with a woman like you. Maybe \
        karmic justice is more about what we need than what we deserve.',
    'I fell in love with you thinking you were perfect. Then I found out you \
        weren\'t, and I loved you even more. The only way we\'re perfect is together.',
    'When you smile, all the problems in my life seem small. Just seeing you outweighs everything else.',
    'When you\'re with me, you make me feel as though I can do anything.',
    'Until I met you, I hadn\'t realized how empty my life was without you. Or \
        how full it was of emptiness. I\'d rather fill it with you.',
    'Because of you, I know what real love is. I can never thank you enough for that.',
    'I won\'t try to speak for you, let alone tell you what to think. But even \
        when we disagree, I will always have your back. And I trust you to have mine.',
    'I don\'t know how you got under my skin. But now I can\'t imagine loving anyone the way I love you.',
    'Don\'t make me choose between your hugs and your kisses. I need both.',
    'You have a gift for listening and for saying what I need to hear — and always with a kind heart.',
    'You\'re everything I\'ve ever wanted and everything I need in my life.',
    'The stars must have been perfectly aligned when I met you, my love.',
    'You inspire me beyond words. I want to be a better man because of you.',
    'I want to be your shoulder to cry on, your protector when you need me, and your lover for life.',
    'How is it possible that you came into my life? I am the luckiest man alive.',
    'I wake up thinking about you. I think of you all day. And when I turn out the light, you are in my dreams.',
    'Sometimes, I am simply breathless when I see you. You are stunning in every possible way.',
    'Would it be wrong to tell you that I never want to live without you? You are my everthing.',
    'My heart aches from loving you so much. It\'s an ache I never want to go away.',
    'I wish you were here so I could hold you tight and breathe in the intoxicating scent of your hair.',
    'Cute Romantic Things to Say to Your Girlfriend',
    'Some expressions of love are perfect for random, cute messages to share \
        with your girlfriend — just because. They\'re spontaneous and heartfelt but not overwhelming.',
    'I smile so much more when I\'m with you that my face muscles are getting a workout.',
    'All I need in this world is you. And I need you here beside me.',
    'Life without you isn\'t a life that I want.',
    'I\'ve never felt more alive than when I\'m with you.',
    'I want to laugh with you every day. Your laughter is my favorite sound in the world.',
    'I still get butterflies whenever I see you. How do you keep doing that?',
    'I want to hold onto you and never let go. You\'re my happy place.',
    'Loving you is like breathing. If I try to stop, everything inside me starts to shut down.',
    'I need you more than I need water. Without water, I\'d last three days.',
    'I\'ve fallen in love hundreds of times. But it\'s always been with you.',
    'Until I met you, I never used to be at a loss for words.',
    'I don\'t think you realize what you\'ve done to me. You\'ve made me better than I ever thought I could be.',
    'If I could wake up next to you every morning, every day would be a good one.',
    'I started growing up the day I met you. You remind me of the person I want to be.',
    'You\'re the reason strangers keep thinking I\'m smiling at them — when I\'m thinking of you. It\'s been awkward.',
    'Seeing you and hearing your voice is all the medicine I need after a rough day. \
        It\'s even better if I can be with you.',
    'I\'m pretty sure you\'re the reason cream does that thing it does when \
        you pour it into coffee. You\'re magic. You make everything a dance.',
    'If I were a stoplight, I\'d turn red every time you pulled up. I still can\'t help it.',
    'I want to make you laugh just so I can see how beautiful you look when you\'re laughing.',
    'A day without you feels like a year. And a day with you passes way too quickly.',
    'Our love is like ocean waves. Sometimes calmly rolling. Sometimes tempestuous. But always there.',
    'I\'m a better human being when I\'m with you. What have you done to me?',
    'I won\'t insult your intelligence by calling you an angel. I was n\' t looking for one, anyway.',
    'Life without you is like a broken pencil. Pointless. But still pokey.',
    'I want to spend the rest of my life with you. And I want the rest of my life to start as soon as possible.',
    'I want to see everything through your eyes. But I wish you could see yourself through mine.',
    'When I let my mind wander, it always ends up with you. You\'re it\'s favorite place to go.',
    'I used to laugh at people who talked about love at first sight. Then I saw you.',
    'I wouldn\'t want to live in a fairy tale unless my happy ending was you.',
    'I don\'t even try to get you off my mind. It\'s better with you in it.',
    'You\'re the only person I\'d want to be stranded on a desert island with.',
    'After all the years we\'ve spent together, you still take my breath away every time I look at you.',
    'How do your kisses set me on fire and calm me down at the same time?',
    'With your beautiful mind and my recklessness, who knows what we could accomplish.',
    'Right now, I want nothing more than to make your day better. You do that for me without even trying.',
    'You\'re the opposite of peer pressure; with you, I feel strong enough to do the right thing.',
    'I\'m never alone when I\'m thinking of you. But when you\'re not here, I miss you so much it hurts.',
    'Conversations with you are never dull. I can\'t wait just to sit and talk with you.',
    'I love listening to you talk. I always learn something. And I love the sound of your voice.',
    'No matter what you\'re wearing, I can\'t take my eyes off you. Or when I do, they want to go right back.',
    'Going out with you gives me the chance to show you off and spoil you at the same time.',
    'You look beautiful today. But then, you do every day.',
    'If I had to, I would wait all my life to be with you. No one else comes close.',
    'couple outside smiling looking on phone romantic things to say to your girlfriend',
    'Just thinking about you in the morning wakes me up. I never thought I\'d actually wake up smiling.',
    'As long as I\'ve got you, I can do anything. We can take on the world together.',
    'Just when I think I can\'t be more in love with you than I am already, you go and prove me wrong.',
    'Can I make you dinner? Just tell me when.',
    'Thanks to you, life has never been better. You are the ultimate upgrade.',
    'You are the music for my dancing. Without you, there\'s neither.',
    'Just looking at you lights me up inside. Darkness doesn\'t stand a chance when I\'m with you.',
    'I used to wonder if love was worth fighting for. Then I met you. I\'m ready for war.',
    'My heart still skips a beat every time you smile at me.',
    'I couldn\'t stop thinking about you last night. Not saying I would have slept much if you\'d been there, either.',
    'You are the human embodiment of the perfect day. And I never want it to end.',
    'You\'re the standard by which I measure every other woman.',
    'You\'re my home. You\'re where I belong and where I want to be.',
    'I can\'t give you the whole world. But I can give you mine. And it\'s all yours.',
    'No one gets me the way you do. No matter what happens, you know exactly what I need to hear.',
    'The sound of your voice instantly makes my day better. Call me anytime!',
    'Thank you for not pretending to be someone else when I met you. I might\'ve \
        missed out on the best thing that ever happened to me.',
    'I only wish I\'d met you sooner. I could have spent more of my life loving you and enjoying your company.',
    'You\'re the only person I know who changed me for the better without even trying to. I love the way you see me.',
    'If you ever left, you\'d leave a hole no one could ever fill. And the rest of me would fall into it.',
    'If folks think I\'m pathetic now, they should see me without you — not that I ever want them to.',
    'Now that I know what life with you is like, I\'m officially ruined for life without you.',
    'You\'re my first thought every morning, my last thought at night, and the best part of every day.',
    'The moment I see you, I wonder what you\'re thinking and how you\'re feeling. \
        I want to be the person you think of first when you need a friend.',
    'I look at you, and I want to relive all the best moments of my life. But this \
        time, I want to enjoy them with you. It\'s as though you always should have been there.',
    'Even when you\'re not smiling, your face is the most beautiful thing I\'ve ever seen.',
    'You make me want to spend more time learning how to be the person you deserve.',
    'If you could see yourself the way I see you, you wouldn\'t be able to take your eyes off you, either.',
    'Even on the worst days, all you have to do to make me smile is show up.',
    'Never thought love languages were a thing. But you definitely know mine. And I want to speak yours all day long.',
    'Let\'s slow dance together, my love, so I have another excuse to hold you close.',
    'I just spent 15 minutes staring at your photo in disbelief that \
        I have the hottest, most beautiful girlfriend ever.',
    'If I think about you hard enough, is it possible to make you materialize right here in front of me?',
    'I am completely and hopelessly love-struck. I can\'t eat. I can\'t sleep. \
        I can\'t do anything except think about being with you.',
    'Why would I settle for being good on my own when life is so much better with you?',
    'You\'re my best friend and the love of my life. I want to grow old with you.'
]
